name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci
  MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }} 

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          
      - name: Install deps
        run: forge install
        
      - name: Create .env file
        run: touch .env && echo MAINNET_RPC_URL=${MAINNET_RPC_URL} > .env && cat .env

      - name: Run tests
        run: forge test
