name: CI
on:
  push:
    branches:
      - master
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          
      - name: Install deps
        run: forge install
        
      - name: Create .env file
        run: echo "${{ secrets.MAINNET_RPC_URL }}" > .env

      - name: Check gas snapshots
        run: forge snapshot --check

      - name: Run tests
        run: forge test
